In [18]:
import numpy as np
from sklearn.model_selection import RepeatedKFold
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4]])
random_state = 12883823
rkf = RepeatedKFold(n_splits=4, n_repeats=1)
for train, test in rkf.split(X):
    print("%s %s" % (train, test))


[0 1 3] [2]
[0 1 2] [3]
[1 2 3] [0]
[0 2 3] [1]


In [3]:
rkf.splo

AttributeError: 'RepeatedKFold' object has no attribute 'splo'

In [19]:
import numpy as np
from sklearn.model_selection import KFold

X = ["a", "b", "c", "d"]
kf = KFold(n_splits=2)
for train, test in kf.split(X):
    print("%s %s" % (train, test))

[2 3] [0 1]
[0 1] [2 3]


In [30]:
X = np.array([[0., 0.], [1., 1.], [-1., -1.], [2., 2.]])
y = np.array([0, 1, 0, 1])
kf = KFold(n_splits=4)
for train, test in kf.split(X):
    X_train, X_test, y_train, y_test = X[train], X[test], y[train], y[test]
    #print("%s %s %s %s" % (X_train, X_test, y_train, y_test))
    #print("%s %s" % (X_train, y_train))
    print("%s %s" % (X_test, y_test))

[[ 0.  0.]] [0]
[[ 1.  1.]] [1]
[[-1. -1.]] [0]
[[ 2.  2.]] [1]


In [21]:
X_train

array([[ 0.,  0.],
       [ 1.,  1.]])

In [22]:
y_train

array([0, 1])

In [23]:
X_test

array([[-1., -1.],
       [ 2.,  2.]])